# Generated by Django 5.1.3 on 2024-12-06 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_personaldetails_phone_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
