# Generated by Django 5.1.4 on 2024-12-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_testmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skill_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.CharField(max_length=50),
        ),
    ]
