# Generated by Django 5.1.4 on 2024-12-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_skill_name_skill_name_alter_skill_proficiency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='description',
        ),
        migrations.RemoveField(
            model_name='education',
            name='user',
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(),
        ),
    ]
